kind: Service
apiVersion: v1
metadata:
  name: maker-bot
  labels:
    app: maker-bot
spec:
  selector:
    app: maker-bot
  ports:
    - port: 9080
      name: http
  type: NodePort
---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: maker-bot
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: maker-bot
        version: v1
    spec:
      containers:
      - name: maker-bot
        image: docker.sebastian-daschner.com/maker-bot:1
        imagePullPolicy: Always
      imagePullSecrets:
      - name: regsecret
      restartPolicy: Always
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: maker-bot
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
  - http:
      paths:
      - path: /maker-bot/.*
        backend:
          serviceName: maker-bot
          servicePort: 9080
---